services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: doncezart
      POSTGRES_PASSWORD: doncezart
      POSTGRES_DB: doncezart
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  db_data:
